### PR TITLE
chore: remove package-lock.json, update Node to > 14

### PR DESCRIPTION
**Pull request by VaiTon**
We don't need two lock files. Let's keep NPM's one.

### CODE REVIEW

**Comment by alexfauquette** [comment]
Could we keep yarn? It's the one used for "hunger games" and "rate my recipes"

**Review by teolemon — APPROVED** [review]

**Comment by VaiTon** [comment]
> Could we keep yarn? It's the one used for "hunger games" and "rate my recipes"

Sure! Can we remove `package-lock.json`?

**Review by teolemon — DISMISSED** [review]
See @alexfauquette 's comment

**Comment by alexfauquette** [comment]
> Sure! Can we remove package-lock.json?

Yes of course. I tried to do it for you but... conflicting with PR merged 😅

**Comment by VaiTon** [comment]
@alexfauquette no prob, I'm doing it :)

**Review by alexfauquette — APPROVED** [review]
Thanks

**Pull request merged**
