### PR TITLE
feat(brands): add getBrands and country function

### PR DESCRIPTION
**Pull request by ms10398**
Add the function to get brands by country.

If no argument is passed default argument is taken as world

Ping @kozlown 

I liked the commit guideline thing, I am learning also with this a lot.

Feels great!

### CODE REVIEW

**Comment by kozlown** [comment]
I think many queries will have the "by country" binding so we should think about it.
Maybe something like
```javascript
OFF.country('fr').getBrands()
```
If you don't know how to implement it I can go deeper in explanation.

**Comment by kozlown** [comment]
Hey, I was meaning something more like [that](https://repl.it/@kozlown/api-example-off).

**Comment by ms10398** [comment]
Okay Yeah I was thinking to do it that way okay will make a commit in few hours @kozlown

**Comment by ms10398** [comment]
In the example the country is coming as undefined in when we log it and it doesn't take the desired country instead it takes world as the default route.

Any ideas about it @kozlown

**Comment by ms10398** [comment]
@kozlown Done all the changes now I think its good to go :laughing:

**Comment by kozlown** [comment]
Remove `request` package and we'll be ok.

**Comment by ms10398** [comment]
Did it :D

**Pull request merged**
