### PR TITLE
chore: clean unused commands and packages in package.json

### PR DESCRIPTION
**Pull request by bengeois**
This pull request cleans up scripts and dependencies :
- `prepack` command is the same as `build`
- `standard` package are not in dependencies and then config and command related to it are not useful anymore
- `formdata-node` is not used in the codebase

### CODE REVIEW

**Comment by VaiTon** [comment]
If I remember correctly prepack is used when the package is installed as a dependency to compile the TS to JS

**Comment by bengeois** [comment]
Actually, the `prepack` command is implicitly used by `npm publish`.

I thought that in the workflow publishing the package, the `yarn build` command was run before `yarn publish`, in this case `yarn prepack` would have been useless.

Do you prefer to modify the workflow publishing the package to add the `yarn build` command before or keep the `yarn prepare` command ?

**Comment by VaiTon** [comment]
I would prefer keeping the alias, as it's very easy to forget to build when doing a manual publish (not that they should be done but nevertheless!)

**Comment by bengeois** [comment]
@VaiTon done!

**Review by VaiTon — APPROVED** [review]

**Pull request merged**
